apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubrtnetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
        - name: kubernetes
          image: kubernetes:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
